---
version: "3.8"

services:
  satisfactory-server:
    build: .
    env_file:
      - .env
    volumes:
      - type: volume # You could also bind-mount this to your local FS (see below)
        source: satisfactory-data
        target: /var/opt/satisfactory/data
      - type: volume
        source: satisfactory-data
        target: /opt/satisfactory/.config/Epic/FactoryGame
    ports:
      - 7777:7777/tcp
      - 7777:7777/udp
      - 15000:15000/tcp
      - 15000:15000/udp
      - 15777:15777/tcp
      - 15777:15777/udp

volumes:
  satisfactory-data:
