---
version: "3.8"

services:
  server:
    build: .
    env_file:
      - .env
    volumes:
      - type: volume
        source: data
        target: /var/opt/satisfactory/data
      - type: volume
        source: data
        target: /opt/satisfactory/.config/Epic/FactoryGame
    ports:
      - 7777:7777/tcp
      - 7777:7777/udp
      - 15000:15000/tcp
      - 15000:15000/udp
      - 15777:15777/tcp
      - 15777:15777/udp
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 6G
        reservations:
          cpus: '0.50'
          memory: 2G

volumes:
  data: null
